services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP для твоего кода
      - "15672:15672"  # Web панель
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbit_data:
